name: temp tests
on: [pull_request]

jobs:
  run-temp-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        id: checkout
      - name: list files
        id: files
        run: |
          git diff 
          git diff --stat
          git checkout --progress --force refs/remotes/pull/2/merge
          